name: Terraform Demos

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    steps:

      # Download repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login   
       run: az login --service-principal --username "<sngupta6@aliazmat6584gmail.onmicrosoft.com>" --password "<Password@8866>" --tenant "<bf6129ba-9b64-4339-b4a4-4a6c4362b313>"
            # Check Azure Subscription
      - name: Check Azure Account
        run: az account show

      # Install/Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

