name: My Azure Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 💥 YEAH LINE SABSE ZAROORI HAI 💥
    runs-on: self-hosted
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a simple test script
        run: |
          echo "Hello! This job is running inside ADISHA machine."
          echo "Current directory is:"
          pwd